name: Build GKI Kernel with China Mirrors

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel Version'
        required: true
        default: '5.10'
        type: choice
        options:
        - '5.10'
        - '5.15'
      target_arch:
        description: 'Target Architecture'
        required: true
        default: 'arm64'
        type: choice
        options:
        - 'arm64'
        - 'arm'

env:
  TSINGHUA_MIRROR: https://mirrors.tuna.tsinghua.edu.cn
  AOSP_MIRROR: https://mirrors.tuna.tsinghua.edu.cn/git/AOSP

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup build environment with China mirrors
      run: |
        # 替换 APT 源为清华镜像
        sudo sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
        sudo sed -i 's/security.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
        sudo apt-get update
        
        # 安装依赖
        sudo apt-get install -y \
          git build-essential libncurses-dev \
          bison flex libssl-dev libelf-dev \
          bc python3 python3-pip wget curl
          
    - name: Clone kernel sources from mirror
      run: |
        git clone ${{ env.AOSP_MIRROR }}/kernel/common.git kernel-source
        cd kernel-source
        
        # 根据版本切换分支
        if [ "${{ github.event.inputs.kernel_version }}" = "5.10" ]; then
          git checkout android12-5.10
        else
          git checkout android13-5.15
        fi
        
    - name: Download toolchain from mirror
      run: |
        git clone ${{ env.AOSP_MIRROR }}/platform/prebuilts/clang/host/linux-x86.git clang-toolchain
        git clone ${{ env.AOSP_MIRROR }}/platform/prebuilts/gas/linux-x86.git gas-toolchain
        
    - name: Build kernel
      run: |
        cd kernel-source
        
        # 设置环境
        export ARCH=${{ github.event.inputs.target_arch }}
        export CLANG_TOOLCHAIN="../clang-toolchain/bin"
        
        # 配置内核
        make ARCH=$ARCH CC="$CLANG_TOOLCHAIN/clang" gki_defconfig
        
        # 应用命名空间配置
        ./scripts/config --file .config -e CONFIG_NAMESPACES
        ./scripts/config --file .config -e CONFIG_UTS_NS
        ./scripts/config --file .config -e CONFIG_IPC_NS
        ./scripts/config --file .config -e CONFIG_USER_NS
        ./scripts/config --file .config -e CONFIG_PID_NS
        ./scripts/config --file .config -e CONFIG_NET_NS
        ./scripts/config --file .config -e CONFIG_MNT_NS
        
        make ARCH=$ARCH olddefconfig
        
        # 编译
        make ARCH=$ARCH CC="$CLANG_TOOLCHAIN/clang" -j$(nproc)
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gki-kernel-${{ github.event.inputs.kernel_version }}-${{ github.event.inputs.target_arch }}
        path: |
          kernel-source/arch/${{ github.event.inputs.target_arch }}/boot/
          kernel-source/.config
